server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: sample-app
    pipeline_stages:
    static_configs:
      - targets:
          - localhost
        labels:
          job: sample-application
          __path__: /etc/promtail/log/*